#!/bin/bash -e
# Copyright 2007-2008 Sun Microsystems, Inc. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
# 
# This code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# only, as published by the Free Software Foundation.
# 
# This code is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License version 2 for more details (a copy is
# included in the LICENSE file that accompanied this code).
# 
# You should have received a copy of the GNU General Public License
# version 2 along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
# 
# Please contact Sun Microsystems, Inc., 16 Network Circle, Menlo
# Park, CA 94025 or visit www.sun.com if you need additional
# information or have any questions.

CELESTEHOME=${CELESTEHOME:=/opt/celeste}
if [[ -x bin/celeste && -x bin/celestefs ]]; then
	CELESTEHOME=`pwd`
fi

replicationParams="AObject.Replication.Store=1;VObject.Replication.Store=1;BObject.Replication.Store=1"
myId=celestefs-writefile
myPassword=pw
fileSystemName=celestefs-writefile-fs
fileSystemPassword=fspw
fileName=celestefs-file
deleteToken=deleteMe
blockSize=`expr 8 \* 1024 \* 1024`
timeToLive=300
echo Time To Live ${timeToLive} seconds
set -x

${CELESTEHOME}/bin/celestefs --verbose --id ${myId} --password ${myPassword} mkid
${CELESTEHOME}/bin/celestefs --verbose --id ${myId} --password ${myPassword} mkfs ${fileSystemName} ${fileSystemPassword}
${CELESTEHOME}/bin/celestefs --verbose --id ${myId} --password ${myPassword} create --attr ReplicationParameters="${replicationParams}" --attr "BlockSize=${blockSize}" --attr "TimeToLive=${timeToLive}" /${fileSystemName}/file
${CELESTEHOME}/bin/celestefs --verbose --id ${myId} --password ${myPassword} pwrite /${fileSystemName}/file 0 < $1
${CELESTEHOME}/bin/celestefs --verbose --id ${myId} --password ${myPassword} ls -l /${fileSystemName}/file
#${CELESTEHOME}/bin/celestefs --id ${myId} --password ${myPassword} pread /${fileSystemName}/file 0 -1
exit 0
