#!/bin/bash -e
# Copyright 2007-2008 Sun Microsystems, Inc. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
# 
# This code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# only, as published by the Free Software Foundation.
# 
# This code is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License version 2 for more details (a copy is
# included in the LICENSE file that accompanied this code).
# 
# You should have received a copy of the GNU General Public License
# version 2 along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
# 
# Please contact Sun Microsystems, Inc., 16 Network Circle, Menlo
# Park, CA 94025 or visit www.sun.com if you need additional
# information or have any questions.

CELESTEHOME=${CELESTEHOME:=/opt/celeste}
if [[ -x bin/celeste && -x bin/celestesh ]]; then
        CELESTEHOME=`pwd`
fi

nameSpaceName=example5
nameSpacePassword=asdf
clientName=example5-client
clientPassword=example5pw
fileName=example5-data

file=/tmp/tester6-junkfile
echo $1 > ${file}
set -x
${CELESTEHOME}/bin/celestesh write-file ${clientName} ${clientPassword} ${nameSpaceName} ${fileName} 0 ${file}        /tmp/d00 /tmp/m00
${CELESTEHOME}/bin/celestesh read-file  ${clientName} ${clientPassword} ${nameSpaceName} ${fileName} 0 -1 -
