#!/bin/bash -e
# Copyright 2007-2008 Sun Microsystems, Inc. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
# 
# This code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# only, as published by the Free Software Foundation.
# 
# This code is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License version 2 for more details (a copy is
# included in the LICENSE file that accompanied this code).
# 
# You should have received a copy of the GNU General Public License
# version 2 along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
# 
# Please contact Sun Microsystems, Inc., 16 Network Circle, Menlo
# Park, CA 94025 or visit www.sun.com if you need additional
# information or have any questions.

CELESTEHOME=${CELESTEHOME:=/opt/celeste}
if [[ -x bin/celeste && -x bin/celestesh ]]; then
        CELESTEHOME=`pwd`
fi

export JVMOPTS="-Xms1024m -Xmx1024m"

file=/tmp/100mb

if ! test -e /tmp/100mb ; then
	dd if=/dev/urandom of=/tmp/100mb bs=1024 count=102400
fi
replicationParams="AObject.Replication.Store=2;VObject.Replication.Store=2;BObject.Replication.Store=2"
nameSpaceName=example3nameSpace
nameSpacePassword=asdf
clientName=example3client
nameSpaceName=example3nameSpace
nameSpacePassword=asdf
clientName=example3client
clientPassword=clientPassword
ownerName=example3owner
ownerPassword=owner
groupName=example3group
groupPassword=group
fileName=example3data
deleteToken=delete
blockSize=`expr 16 \* 1024 \* 1024`
blockSize=`expr 8 \* 1024 \* 1024`
#blockSize=`expr 4 \* 1024 \* 1024`
#blockSize=`expr 2 \* 1024 \* 1024`
#blockSize=`expr 1 \* 1024 \* 1024`
timeToLive=86400
signWrites="--signed-writes"

set -x
${CELESTEHOME}/bin/celestesh new-credential  ${nameSpaceName} ${nameSpacePassword} ${replicationParams}
${CELESTEHOME}/bin/celestesh new-credential  ${ownerName} ${ownerPassword} ${replicationParams}
${CELESTEHOME}/bin/celestesh new-credential  ${groupName} ${groupPassword} ${replicationParams}
${CELESTEHOME}/bin/celestesh new-credential  ${clientName} ${clientPassword} ${replicationParams}
${CELESTEHOME}/bin/celestesh read-credential ${clientName} /tmp/cred-d /tmp/cred-m

${CELESTEHOME}/bin/celestesh create-file     ${signWrites} ${clientName} ${clientPassword} ${nameSpaceName} ${nameSpacePassword} ${fileName} ${ownerName} ${groupName} ${deleteToken} ${replicationParams} ${blockSize} ${timeToLive} /tmp/create-d /tmp/create-m

time ${CELESTEHOME}/bin/celestesh write      ${clientName} ${clientPassword} ${nameSpaceName} ${fileName} 0 ${file}        /tmp/d00 /tmp/m00
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
	${CELESTEHOME}/bin/celestesh --verbose read  ${clientName} ${clientPassword} ${nameSpaceName} ${fileName} 4 0 -1             /tmp/d01
	cmp /tmp/d01 ${file}
done
